{
  "jsonrpc": "2.0",
  "id": 8,
  "method": "createWorkspace",
  "params": {
    "contextUrl": "https://github.com/Cyfrin/foundry-simple-storage-f23",
    "mode": "default",
    "forceDefaultConfig": true
  }
}